---
title: "pHacking_tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pHacking_tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(easypackages)
packages <- c('tidyverse', 'MASS', 'devtools', 'parallel', 'pbmcapply', 'data.table')
libraries(packages)
load_all()
```


```{r echo=F}
##Example: Consider a developmental researcher with an archival data base containing data for several dependent and independent variables. For example,
##data on shyness, anxiety, self-reported stress, happiness exists for children. Among these data, the researcher can group the data in several ways:
#sex, race, SES, attachment style, etc. Thus, there is an ample opportunity to conduct pairwise comparisons in an uncontrolled manner.

#Factors to simulate:
##1) Cell size: 30, 50, 100, 300, 500
##2) Selective reporting with respect to the IV (3, 5, 10 groups). Each group has two levels and a t test is computed between the two levels
##(i.e., control vs test). A comparison is reported only if it is significant.
##3) Selective reporting with respect to the DV (3, 5, 10 variables). Data for each DV exists for each group. Thus, if there are 3 groups and 3 DVs,
##then data for each DV provides data for 3 groups (i.e., 3 t-tests), meaning a total of 9 t-tests are computed.
##4) Correlation among DVs (0.16; average correlation in I-O psychology).
##5) Correlation among IV levels (0.16; average correlation in I-O psychology). Correlation between IVs would zero, otherwise they would cease to be independent.
##for the desired number of variables.
##6) Optional stopping (N_add = 5, 10, 50) with Nmax = {30, 50, 100, 300, 500} 
##7) Variable transformations (logarithmic, reciprocal, square root transformation) on DV, predictor, or both. 
##8) Missing data (MCAR or MNAR with percentages of 10%, 30%, and 50% (see Peugh & Enders, 2004). 


## Additional conditions to simulate under
##1) Missing data (missing not at random: the probability that a value is missing depends on the missing data value themselves) For example, probability of
##response decreases with value on variable. Manipulate percentages to be 10%, 30%, and 50% (see Peugh & Enders, 2004). Mean percentage of missing data was 7.60%, with average of
##7.09% in cross-sectional designs and 9.78% in longitudinal designs.
##2) Measurement error

##Measurement of false positive rate.
##First, understand that the false positive rate is a measure of incidence in a family of tests. A family of tests is determined by the factors that
##manipulated. For example, if there are 3 groups and three DVs, then a family of tests would contains 9 t tests. If any of these tests returns
##significant, then the
#False positive rate: proportion of

##P-value selection method
##1) First significant
##2) Smallest p-value

#Optional stopping
##Simulated by adding the desired number of data points and repeating the transaction. The new list of p_values are added to the current one. The 
##procedure is repeated until the maximum sample is obtained. Optional stopping will be manipulated by using a more realistic manipulation than used in 
## Stefan et al. (2022). Nmax = {30, 50, 100, 250, 500} and step size = {10, 25, or 50}. 

#Covariates
##Simulated by computing bivariate regression and then adding covariates one at a time. Number of covariates = {3, 5, 10}. Correlation of covariates is .16 or .30. 

#Transformations
###Simulated by using logarithmic, reciprocal, and square root transformations on DV, predictor, or both. 

#Discretizing variables
##Simulated by conducting median split on continuous variable or cut-the-middle split. 

#Missing data
##Simulated by having data be MCAR or MNAR for 10, 30, or 50% of the data. 

#for each sample size increment, generate a data set with that many data poins 
sim_params <- list('step_size' = 10,
                   'n_min' = c(30, 50, 100, 300), 
                   'n_max' = c(30, 50, 100, 300), 
                   'num_dvs' = c(3, 5, 10), 
                   'num_ivs' = 1, 
                   'dv_cor' = c(0, 0.3, 0.8), 
                   'iv_cor' = 0)


sim_data <- run_exp_simulations(sim_params = sim_params, num_iterations = 3, num_cores = 3, seed = 27, step_size =F )
sim_data$false_pos_exist <- sapply(X = 1:nrow(sim_data), FUN = false_pos_exist, sim_data = sim_data)



```





